### ISSUE TITLE
Issues DynamoDB Credential concern

### ISSUE THREAD

**Issue by coconutking** [tgandrews/next-auth-dynamodb#14]
I have a working aws dynamodb api separate from nextauth working on vercel, but when I try to login with the email I get a 502 error. I think I might be having a problem setting up my dynamodb for omanyd. This is how I am assigning my process env for omanyd in [...nextauth].ts

I have PA_AWS_ACCESS_KEY_ID, PA_AWS_SECRET_ACCESS_KEY, PA_AWS_REGION assigned in vercel.

> import NextAuth from 'next-auth';
import Providers from 'next-auth/providers';
import dynamodbAdapter from 'next-auth-dynamodb';

>process.env.OMANYD_AWS_ACCESS_KEY_ID = process.env.PA_AWS_ACCESS_KEY_ID;
process.env.OMANYD_AWS_SECRET_ACCESS_KEY = process.env.PA_AWS_SECRET_ACCESS_KEY;
process.env.OMANYD_AWS_REGION = process.env.PA_AWS_REGION;

>const options = {
    // Configure one or more authentication providers
    site: process.env.NEXTAUTH_URL,
    providers: [
        Providers.Email({
            server: process.env.EMAIL_SERVER,
            from: process.env.EMAIL_FROM,
        }),
    ],
    adapter: dynamodbAdapter,
    events: {},
    debug: false,
};

>export default (req, res) => NextAuth(req, res, options);

Error from Local Sandbox
![image](https://user-images.githubusercontent.com/3861899/103946331-4fb91b80-50eb-11eb-9206-62197d1137be.png)

Appreciate your plugin and attention you have given me in trying to guide me through this.

**Comment by coconutking** [comment]
I tried assigning directly the omanyd access key directly and now I am getting a requested resource not found when I submit the email for login. Is there a certain way to setup dynamodb tables or permissions for omanyd or next-auth-dynamodb that I might be missing from the readme? Thanks for your time.

> (node:7671) UnhandledPromiseRejectionWarning: ResourceNotFoundException: Requested resource not found
    at Request.extractError (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/www/productarc/product-arc/node_modules/omanyd/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:7671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error! Failed to complete request to /api/auth/signin/email: Error: socket hang up

**Comment by tgandrews** [comment]
Thanks for creating the issue.

The `ResourceNotFound` sounds like the tables haven't been created. 

I'll add [cdk](https://github.com/aws/aws-cdk) definitions but you can also create them through the AWS cli or web console.
Locally however I call seedSession after I spin up dynamodb in docker. `seedSession` will automatically create the necessary tables.

**Comment by coconutking** [comment]
Thank you so much for the updated README. I will try to update my AWS setup and noticed I should have used the omanyd schema setup https://github.com/tgandrews/next-auth-dynamodb/blob/main/src/index.ts#L17

Also if you are working on any side projects I would love to support them in anyway. What is the best way to do that? If you are contracting My instagram/twitter at memoryfab
