### ISSUE TITLE
Verification requests

### ISSUE THREAD

**Issue by johnaxe** [tgandrews/next-auth-dynamodb#18]
Great job with the dynamodb adapter. I currently run it on lambda@edge and it works flawlessly.
Except for .. verification_requests which seems to not have been implemented.
Is it maybe an upcoming feature? It would be a great addition to an already great package.
As it is now, I cannot use passwordless auth by email

**Comment by tgandrews** [comment]
Thanks @johnaxe. This has just been resolved in issue #16 but not yet released.

I don't yes email login in any of my apps so haven't tried it in anger anywhere. Would you be willing to try it? There is a comment on that issue to explain how.
